# permissions for end users to edit managedapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedapplication-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
  name: managedapplication-editor-role
rules:
- apiGroups:
  - kubedevaiops.kubedevaiops.com
  resources:
  - managedapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubedevaiops.kubedevaiops.com
  resources:
  - managedapplications/status
  verbs:
  - get
