---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubedevaiops.kubedevaiops.com
  resources:
  - airequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubedevaiops.kubedevaiops.com
  resources:
  - airequests/finalizers
  verbs:
  - update
- apiGroups:
  - kubedevaiops.kubedevaiops.com
  resources:
  - airequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubedevaiops.kubedevaiops.com
  resources:
  - managedapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubedevaiops.kubedevaiops.com
  resources:
  - managedapplications/finalizers
  verbs:
  - update
- apiGroups:
  - kubedevaiops.kubedevaiops.com
  resources:
  - managedapplications/status
  verbs:
  - get
  - patch
  - update
