apiVersion: kubedevaiops.kubedevaiops.com/v1alpha1
kind: Foo
metadata:
  labels:
    app.kubernetes.io/name: foo
    app.kubernetes.io/instance: foo-sample
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app
  name: foo-sample
spec:
  # TODO(user): Add fields here
